name: examcoach_app
description: A comprehensive exam preparation app for Nigerian educational assessments
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10
  
  # State Management
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  
  # Navigation
  go_router: ^14.2.0
  
  # HTTP & API
  dio: ^5.5.0
  
  # Data & Serialization
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  
  # Local Database
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.4
  path: ^1.9.0
  
  # Storage
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  
  # Notifications
  flutter_local_notifications: ^17.2.1
  
  # Firebase
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  firebase_analytics: ^11.3.3
  
  # Charts & Visualization
  fl_chart: ^0.68.0
  
  # Platform Integration
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.1
  connectivity_plus: ^6.0.3
  uni_links: ^0.5.1
  webview_flutter: ^4.8.0
  in_app_purchase: ^3.2.0
  
  # Utilities
  uuid: ^4.4.0
  intl: ^0.19.0
  archive: ^3.6.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Code Generation
  build_runner: ^2.4.11
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  drift_dev: ^2.18.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/images/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
